### ISSUE TITLE
w3w-arcgis-webappbuilder-widget issue

### ISSUE THREAD

**Issue by suhaib87a** [what3words/w3w-arcgis-webappbuilder-widget#3]
Dear Support,

I’m using the what3words widget and deployed it in my web app, the widget works fine in windows platform but when trying to use it via touch screen devices (IOS/Android) it does not recognize the touch.

Is it OS platform related issue or Click/Touch event related issue?
How to make it work  in all devices?

Regards,
Suhaib suleiman

**Comment by tsamaya** [comment]
Hi
Thanks for your enquiry.

The issue has been fixed in the new release of the widget (from the PR #4 )

Regards
Arnaud from what3words devteam
