### ISSUE TITLE
Widget not working in existing experience

### ISSUE THREAD

**Issue by pattyjula** [what3words/w3w-arcgis-webappbuilder-widget#8]
Hello, I reached out to my vendor and I'm cross posting over here. This widget is working just fine in a new experience builder, but does not show the three words if I add the widget to an existing experience. Below is an image of the widget working properly in a new experience.

![Widget working properly in an empty experience](https://user-images.githubusercontent.com/5982211/189742288-0efe5bb3-6d00-4fca-b61f-3d8365e26329.PNG)

Below is an example of the widget not displaying the three words. I have tested this a few different times. Maybe the fact that there are features to identify in this map is interfering with the three words identification? The lat/long are displaying just fine in both maps though. Thank you very much for your feedback!

![Widget not displaying three words](https://user-images.githubusercontent.com/5982211/189742605-537a2599-919c-4e80-b057-2d7c84bd0547.PNG)

**Comment by pattyjula** [comment]
Hey I dug into the widget a little more and think something needs to be constructed on the `mapClick` method to handle  feature layers in a map. Again, this widget works properly in a map that is just a base map, but has not provided the three words when the widget is added to a map that has feature layers.

`const graphic = await getMarkerGraphic(mapClick.mapPoint)`

**Comment by ManuCiao** [comment]
hey @pattyjula thanks for flagging this issue, but I think you have posted on the wrong repository since this one is for the ArcGIS Web AppBuilder widget. Anyways I will look into it and transfer this issue to this repository [https://github.com/what3words/w3w-arcgis-experience-builder-widget](https://github.com/what3words/w3w-arcgis-experience-builder-widget).

**Comment by ManuCiao** [comment]
hi @pattyjula sorry for the delay.
I have fixed the issue on this repo https://github.com/what3words/w3w-arcgis-experience-builder-widget 
you can now test the what3words widget on maps that have already layers. Please let me know if that fixed the issue you were having.
